/*
 Copyright (c) Ron Coleman

 Permission is hereby granted, free of charge, to any person obtaining
 a copy of this software and associated documentation files (the
 "Software"), to deal in the Software without restriction, including
 without limitation the rights to use, copy, modify, merge, publish,
 distribute, sublicense, and/or sell copies of the Software, and to
 permit persons to whom the Software is furnished to do so, subject to
 the following conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
/**
 * These classes implement serial, mapreduce, and parallel collection implementations.
 * Table below was generated by http://divtable.com/generator/
 * <p>
 *<table>
 <tbody>
 <tr>
 <td>&nbsp;File</td>
 <td>&nbsp;Goal</td>
 </tr>
 <tr>
 <td>Ser00.scala</td>
 <td>&nbsp;Sequential naive sequential over portfolios, sequential over bonds</td>
 </tr>
 <tr>
 <td>Ser01.scala</td>
 <td>&nbsp;Sequential memory-bound</td>
 </tr>
 <tr>
 <td>Ser02.scala</td>
 <td>&nbsp;(Same as Ser00, different syntax)</td>
 </tr>
 <tr>
 <td>Ser03.scala&nbsp;</td>
 <td>&nbsp;(Same as Ser01, different syntax)</td>
 </tr>
 <tr>
 <td>Mr00.scala</td>
 <td>&nbsp;Mapreduce parallel small number portfolios</td>
 </tr>
 <tr>
 <td>Mr01.scala&nbsp;</td>
 <td>&nbsp;Mapreduce parallel arbitrary number portfolios</td>
 </tr>
 <tr>
 <td>Mr02.scala&nbsp;</td>
 <td>&nbsp;Mapreduce coarse-grain parallel</td>
 </tr>
 <tr>
 <td>Mr03.scala&nbsp;</td>
 <td>&nbsp;Mapreduce memory-bound parallel&nbsp;over portfolios, sequential reduce over bonds</td>
 </tr>
 <tr>
 <td>Mr04.scala</td>
 <td>&nbsp;Mapreduce fine-grain parallel&nbsp;parallel&nbsp;over portfolios, parallel reduce over bonds</td>
 </tr>
 <tr>
 <td>Mr05.scala</td>
 <td>&nbsp;Mapreduce sequential / parallel alternating&nbsp;</td>
 </tr>
 <tr>
 <td>Par00.scala</td>
 <td>Composite parallel naive</td>
 </tr>
 <tr>
 <td>Par01.scala</td>
 <td>Memory-bound parallel naive</td>
 </tr>
 <tr>
 <td>Par02.scala</td>
 <td>Memory-bound parallel&nbsp;over portfolios, sequential reduce over bonds</td>
 </tr>
 <tr>
 <td>Par03.scala</td>
 <td>Composite parallel over portfolios parallel reduce over bonds</td>
 </tr>
 <tr>
 <td>Par04.scala</td>
 <td>Coarse-grain parallel naive</td>
 </tr>
 <tr>
 <td>Par05.scala</td>
 <td>(Same as Par03 except different syntax)</td>
 </tr>
 <tr>
 <td>Par06.scala</td>
 <td>Fine-grain memory-bound parallel</td>
 </tr>
 <tr>
 <td>Par07.scala</td>
 <td>Coarse-grain memory-bound parallel</td>
 </tr>
 </tbody>
 </table>
 </p>
 */
package parabond.test;
